### ISSUE TITLE
jquery ajax vervangen door fetch

### ISSUE THREAD

**Issue by ghost** [StudentROCTilburg2/wandelapp_issues#5]
jQuery wordt alleen gebruikt voor een AJAX request in routes.js.
Kan dit niet vervangen worden door de nieuwe fetch API?

jQuery wordt ook gebruikt in hikingapp.js. jQuery blijft dus nodig. Update van routes.js is in ieder geval wel nodig.

**Comment by StudentROCTilburg2** [comment]
Uit gesprek met opdrachtgever is toestemming gekregen om JQuery uit het gehele project te verwijderen.

**Comment by StudentROCTilburg2** [comment]
Ajax vervangen met fetch en heel Jquery dependeny niet meer nodig.
